### ISSUE TITLE
Able to run all python tests..

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-python#27]
Was logging into the bridges testing to check the visualizations, but got an int ernal server error.

But yeah, I had jsut the PYTHONPATH set from last night (when it didnt work)  and all tests completed successfully.  Some magic over night from Alec/Erik!

**Comment by krs-world** [comment]
Are we ready to finalize the Java and C++ versions?  I saw some changes in Java last night, but not in C++.   I will need to do some work to get it to the site, generate doxygen docs, etc. Update the web tests (that should just be a copy and push to the site, not a biggie).

**Comment by esaule** [comment]
there were changes in the c++ version fixing the json parsing of colorgrid. the c++ client could parse graphs but that broke recently with the clone assignment json changed. i'll fix later.

On January 4, 2019 12:54:32 PM EST, Kalpathi Subramanian <notifications@github.com> wrote:
>Are we ready to finalize the Java and C++ versions?  I saw some changes
>in Java last night, but not in C++.   I will need to do some work to
>get it to the site, generate doxygen docs, etc. Update the web tests
>(that should just be a copy and push to the site, not a biggie).
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/krs-world/bridges-python/issues/27#issuecomment-451518369

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
