### ISSUE TITLE
avl tree tutorial.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-python#9]
AVL tree as it is derived from BST should show the key value by default. The label (balance factor in the example) shows up by mouse hover or turning on labels.

**Comment by krs-world** [comment]
Looks like the BST visualization is not displaying the key by default. David, is this an issue on the server side?  Or is the JSON not sending the key field?  The latter could account for it.

**Comment by quaiquai** [comment]
I had a section of that code commented out. I can fix that.

**Comment by krs-world** [comment]
Was this done?

**Comment by AlecGoncharow** [comment]
http://bridgesuncc.github.io/Hello_World_Tutorials/AVL.html
appears to be done, closing
